_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 55
                - 61
            "4": 3.11.9
            "5": 0.20.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.20.1
            "13": windows-amd64
data_settings:
    value:
        eval_seed: 42
        "n": 4
        run_base_dir: runs_re_arc
        training_keys:
            - 00d62c1b
            - 1cf80156
            - 25d8a9c8
            - 0a938d79
        training_seed: 42
evaluation_settings:
    value:
        eval_epoch: 10
        eval_keys:
            - 00d62c1b
        eval_n_queries: 10
        eval_n_samples: 2
        visualize_n_values: 2
latent_optimization:
    value:
        evolutionary:
            mutation_std: 0.5
            num_generations: 100
            population_size: 25
        inference:
            enabled: true
            learning_rate: 0.1
            num_steps: 100
        method: gradient
        training:
            enabled: false
            learning_rate: 0.1
            num_steps: 1
        voronoi:
            diversity_weight: 0.5
            mutation_std: 0.1
            num_generations: 15
            population_size: 10
model_architecture:
    value:
        decoder_heads: 6
        decoder_hidden_dim: 96
        decoder_layers: 2
        decoder_max_length: 902
        dropout: 1e-06
        encoder_heads: 6
        encoder_hidden_dim: 96
        encoder_layers: 2
        encoder_max_length: 1805
        latent_dim: 128
        max_length: 902
        num_encoders: 4
        use_gradient_checkpointing: true
training_settings:
    value:
        batch_size: 2
        beta: 0.01
        gradient_accumulation_steps: 2
        learning_rate: 0.0004
        learning_rate_scheduler:
            lr_min: 1e-06
            type: none
            warmup_epochs: 20
        num_epochs: 3
        optimizer_weight_decay: 1e-05
        save_checkpoint_interval: 1
        solo_loss:
            enabled: true
            isolate_decoder_gradients: true
            lambda_solo: 0.2
            log_frequency: 100
        use_mixed_precision: true
        wandb:
            api_key: e2853fdc991b057f1cebf7df2a747ecca6fdaf6c
            enabled: true
            entity: ga624-imperial-college-london
            log_gradients: false
            log_interval: 1
            log_visualizations: true
